### ISSUE TITLE
Cleanup passes

### ISSUE THREAD

**Issue by aditink** [aditink/algebraic_simplification_cesar#3]
Identify any common methods or functionality that repeat across different classes, and put them in a library that these passes can consume.

**Comment by aditink** [comment]
@ravneetsb is working on this.

**Comment by Ravneetsb** [comment]
https://github.com/aditink/algebraic_simplification_cesar/pull/4

**Comment by Ravneetsb** [comment]
https://github.com/aditink/algebraic_simplification_cesar/pull/14

**Comment by Ravneetsb** [comment]
https://github.com/aditink/algebraic_simplification_cesar/pull/19
